# Generated by Django 4.0.2 on 2022-02-09 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('employer', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
                ('experience', models.CharField(max_length=50)),
                ('requirements', models.CharField(max_length=50)),
            ],
        ),
    ]
