# Generated by Django 4.0.2 on 2022-03-15 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameindustry', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='time_scraped',
            field=models.DateTimeField(default=None),
            preserve_default=False,
        ),
    ]
